# Generated by Django 5.2.12 on 2026-03-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='mon_app_eve_start_d_5ece37_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=0, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='mon_app_eve_date_10e34a_idx'),
        ),
    ]
